sudo: required
services:
  - docker
before_install:
  - docker build -t psathishkreddy/docker-react -f Dockerfile.dev .
script:
  - docker run psathishkreddy/docker-react npm test  -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker"
  env: "Docker-React-env"
  bucket_name: "elasticbeanstalk-us-east-2-727947047375"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"